### ISSUE TITLE
MPRAmodel line 430

### ISSUE THREAD

**Issue by amysorekar** [tewhey-lab/MPRAmodel#1]
Hi, I'm in the Sahni Lab. I'm going over this code and translating it to pseudocode. I noticed on line 430 that there is a loop that iterates through cell_ids, yet cell_ids hasn't been defined yet. Later, in the else if, there is also a loop that goes over cell_ids, but in this case cell_ids has been defined as a dataframe. Perhaps line 430 meant to say plas_ids?

**Comment by deweyhannah** [comment]
Yes Thanks! Fixing it now now
